name: Reproduction
on:
  workflow_dispatch:

permissions: {}

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - parallel:
          - uses: runs-on/cache@88d90644011a3a9957fd141a106f5a94f9794203
            with:
              key: a
          - uses: runs-on/cache@88d90644011a3a9957fd141a106f5a94f9794203
            with:
              key: b
