name: Reproduction
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - parallel:
          - uses: ./.github/actions/setup-a
          - uses: ./.github/actions/setup-b
